{
 "title": "Job Applications Tracker",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Daily Chart", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Daily Completed Applications",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "jobapps",
     "rawSql": "SELECT count(app_id) count,FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(date)/86400)*86400) time\n\nfrom jobapps.applications\n\ngroup by time;\n-- divide by seconds 900=15mins"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Completed Applications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "jobapps",
     "rawSql": "SELECT count(app_id) count,FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(date)/3600)*3600) time\n\nfrom jobapps.applications\n\ngroup by time;\n-- divide by seconds 900=15mins"
    }
   ]
  },
  {
   "title": "Completed Applications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "targets": [
    {
     "dataset": "jobapps",
     "rawSql": "SELECT count(app_id) count,FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(date)/60)*60) time\n\nfrom jobapps.applications\n\ngroup by time\norder by time desc\nlimit 77200;\n-- divide by seconds 900=15mins"
    }
   ]
  },
  {
   "title": "[blue Completed] Applications Log",
   "type": "table",
   "description": "Filtered",
   "gridPos": { "h": 19, "w": 13, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "jobapps",
     "rawSql": "SELECT date, company_name, title, id, B.app_id\n FROM jobapps.postings\n\nLEFT JOIN \n(select app_id, posting_id from jobapps.applications) B\nON id=posting_id\n\n ORDER BY date DESC \n LIMIT 500 "
    }
   ]
  },
  {
   "title": "Completed Applications",
   "type": "table",
   "gridPos": { "h": 19, "w": 11, "x": 13, "y": 16 },
   "targets": [
    {
     "dataset": "jobapps",
     "rawSql": "SELECT postings.date, postings.id, company_name, title \n\nFROM jobapps.applications inner join postings on id=posting_id order by postings.date desc;"
    }
   ]
  },
  {
   "title": "Company Hit Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "jobapps",
     "rawSql": "select min(company_name) company_name, count(id) n FROM\n(select id, app_id, company_name, applications.date from jobapps.applications\nleft join jobapps.postings on\nid=posting_id) A\n\nwhere company_name <> \"\"\n\ngroup by company_name \norder by n desc"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "dataset": "jobapps",
     "rawSql": "SELECT MIN(company_name), COUNT(id) FROM jobapps.postings WHERE COALESCE(company_name, '') <> '' GROUP BY company_name LIMIT 50 "
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 19, "w": 13, "x": 0, "y": 43 },
   "targets": [
    {
     "dataset": "jobapps",
     "rawSql": "SELECT date, company_name, title FROM jobapps.postings ORDER BY date DESC LIMIT 50 "
    }
   ]
  }
 ]
}